# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d2a37bdf85041286af8dc2b5160fd7d96c83b3a0ff074c26d196655ae020d57d256ae587179a7ed418f6c58cb4d3a3123f269bf349121cf3a1b353d79b97a01

test:
  secret_key_base: 778ddaa35d1e18d56ae19c20fd85c351d910d8bc43dbd89d103d5409e5c68d4175017d59791db4610823b24be848b11f4ce0ab044123691c6874431d7eacc052

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
